name: generate markdown

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: plzprayme/online-judge-directory-tree-to-readme@application

